/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorsRouteImport } from './routes/tutors'
import { Route as BecomeTutorRouteImport } from './routes/become-tutor'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorsIndexRouteImport } from './routes/tutors.index'
import { Route as TutorsIdRouteImport } from './routes/tutors.$id'
import { Route as DashboardIdRouteImport } from './routes/dashboard.$id'
import { Route as BookIdRouteImport } from './routes/book.$id'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as TutorsIdOfferingSubjectRouteImport } from './routes/tutors.$id.offering.$subject'

const TutorsRoute = TutorsRouteImport.update({
  id: '/tutors',
  path: '/tutors',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeTutorRoute = BecomeTutorRouteImport.update({
  id: '/become-tutor',
  path: '/become-tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorsIndexRoute = TutorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TutorsRoute,
} as any)
const TutorsIdRoute = TutorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TutorsRoute,
} as any)
const DashboardIdRoute = DashboardIdRouteImport.update({
  id: '/dashboard/$id',
  path: '/dashboard/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const TutorsIdOfferingSubjectRoute = TutorsIdOfferingSubjectRouteImport.update({
  id: '/offering/$subject',
  path: '/offering/$subject',
  getParentRoute: () => TutorsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-tutor': typeof BecomeTutorRoute
  '/tutors': typeof TutorsRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/book/$id': typeof BookIdRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/tutors/$id': typeof TutorsIdRouteWithChildren
  '/tutors/': typeof TutorsIndexRoute
  '/tutors/$id/offering/$subject': typeof TutorsIdOfferingSubjectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-tutor': typeof BecomeTutorRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/book/$id': typeof BookIdRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/tutors/$id': typeof TutorsIdRouteWithChildren
  '/tutors': typeof TutorsIndexRoute
  '/tutors/$id/offering/$subject': typeof TutorsIdOfferingSubjectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/become-tutor': typeof BecomeTutorRoute
  '/tutors': typeof TutorsRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/book/$id': typeof BookIdRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/tutors/$id': typeof TutorsIdRouteWithChildren
  '/tutors/': typeof TutorsIndexRoute
  '/tutors/$id/offering/$subject': typeof TutorsIdOfferingSubjectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/become-tutor'
    | '/tutors'
    | '/profile'
    | '/book/$id'
    | '/dashboard/$id'
    | '/tutors/$id'
    | '/tutors/'
    | '/tutors/$id/offering/$subject'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/become-tutor'
    | '/profile'
    | '/book/$id'
    | '/dashboard/$id'
    | '/tutors/$id'
    | '/tutors'
    | '/tutors/$id/offering/$subject'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/become-tutor'
    | '/tutors'
    | '/_authenticated/profile'
    | '/book/$id'
    | '/dashboard/$id'
    | '/tutors/$id'
    | '/tutors/'
    | '/tutors/$id/offering/$subject'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BecomeTutorRoute: typeof BecomeTutorRoute
  TutorsRoute: typeof TutorsRouteWithChildren
  BookIdRoute: typeof BookIdRoute
  DashboardIdRoute: typeof DashboardIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutors': {
      id: '/tutors'
      path: '/tutors'
      fullPath: '/tutors'
      preLoaderRoute: typeof TutorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-tutor': {
      id: '/become-tutor'
      path: '/become-tutor'
      fullPath: '/become-tutor'
      preLoaderRoute: typeof BecomeTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutors/': {
      id: '/tutors/'
      path: '/'
      fullPath: '/tutors/'
      preLoaderRoute: typeof TutorsIndexRouteImport
      parentRoute: typeof TutorsRoute
    }
    '/tutors/$id': {
      id: '/tutors/$id'
      path: '/$id'
      fullPath: '/tutors/$id'
      preLoaderRoute: typeof TutorsIdRouteImport
      parentRoute: typeof TutorsRoute
    }
    '/dashboard/$id': {
      id: '/dashboard/$id'
      path: '/dashboard/$id'
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof DashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/tutors/$id/offering/$subject': {
      id: '/tutors/$id/offering/$subject'
      path: '/offering/$subject'
      fullPath: '/tutors/$id/offering/$subject'
      preLoaderRoute: typeof TutorsIdOfferingSubjectRouteImport
      parentRoute: typeof TutorsIdRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface TutorsIdRouteChildren {
  TutorsIdOfferingSubjectRoute: typeof TutorsIdOfferingSubjectRoute
}

const TutorsIdRouteChildren: TutorsIdRouteChildren = {
  TutorsIdOfferingSubjectRoute: TutorsIdOfferingSubjectRoute,
}

const TutorsIdRouteWithChildren = TutorsIdRoute._addFileChildren(
  TutorsIdRouteChildren,
)

interface TutorsRouteChildren {
  TutorsIdRoute: typeof TutorsIdRouteWithChildren
  TutorsIndexRoute: typeof TutorsIndexRoute
}

const TutorsRouteChildren: TutorsRouteChildren = {
  TutorsIdRoute: TutorsIdRouteWithChildren,
  TutorsIndexRoute: TutorsIndexRoute,
}

const TutorsRouteWithChildren =
  TutorsRoute._addFileChildren(TutorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BecomeTutorRoute: BecomeTutorRoute,
  TutorsRoute: TutorsRouteWithChildren,
  BookIdRoute: BookIdRoute,
  DashboardIdRoute: DashboardIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
